### PR TITLE
added in nickname #83, language, verified, and tagline to person

### PR DESCRIPTION
**Pull request by denov**
i really needed language so i added with a couple others that looked useful.  it would be great to see these in something like 1.0.1 and in maven central. 

all tests pass in Idea but won't pass with gradlew.

### CODE REVIEW

**Comment by denov** [comment]
any idea when we'll see this change in a release?

**Comment by mlaccetti** [comment]
Will see if I can cut a release in a day or two.

**Comment by wabson** [comment]
Any chance the fixes on develop could be merged in before the release?

**Comment by mlaccetti** [comment]
I'll see what I can do.



On Sat, May 7, 2016 at 4:55 AM -0700, "Will Abson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Any chance the fixes on develop could be merged in before the release?

-

**Pull request merged**
